[package]
name = "ufb"
version = "0.1.0"
edition = "2024"

[lib]
name = "ufb"
crate-type = ["rlib", "cdylib"]

[dependencies]
opener = { git = "https://github.com/paring-chan/opener.git", rev = "36412b7cec2445065669ebe9af02df5480c10550", features = [
    "reveal",
] }
rfd = "0.15.3"
