[package]
name = "ufb"
version = "0.1.0"
edition = "2024"

[lib]
name = "ufb"
crate-type = ["rlib", "cdylib"]

[dependencies]
opener = { version = "0.8.2", features = ["reveal"] }
raw-window-handle = "0.6.2"
rfd = "0.15.3"

[dependencies.windows]
version = "0.61.1"
features = ["Win32_UI_WindowsAndMessaging"]
