[package]
name = "ufb"
version = "0.1.0"
edition = "2024"

[lib]
name = "ufb"
crate-type = ["rlib", "cdylib"]

[dependencies]
opener = { version = "0.8.2", features = ["reveal"] }
raw-window-handle = "0.6.2"
rfd = "0.15.3"
ufb-native = { path = "../ufb-native" }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.61.1"
features = ["Win32_UI_WindowsAndMessaging"]

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.1"
objc2-app-kit = "0.3.1"
# objc2-foundation = "0.3.1"
dispatch2 = "0.3.0"
